### PR TITLE
Fix(Catalog): Make latest RHBAC version the default selection

### LINKED ISSUE #1955: Make latest RHBAC version the default selection

### PR DESCRIPTION
**Pull request by shivamG640**
Fixes #1955

### CODE REVIEW

File: packages/ui/src/utils/version-compare.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+/**
+ * Compare the version of camel catalogs
+ *
+ * @param v1 The first version.
+ * @param v2 The second version.
+ * @returns The weight of the schema against the model.
```
Comment (lordrip) [inline packages/ui/src/utils/version-compare.ts:6]: Could it be possible to explain the return of the function like we're doing for the tests? I think this description might not be 100% accurate :)

Comment (shivamG640) [reply packages/ui/src/utils/version-compare.ts:6]: That's an incorrect statement. Thanks for the catch!

**Comment by lhein** [comment]
something strange is going on with the UI Tests. Please take a closer look at it.

**Comment by shivamG640** [comment]
> something strange is going on with the UI Tests. Please take a closer look at it.

Thanks for catching those issues in Storybook. The Red Hat version of the Camel Main catalog didn't include the ActiveMQ and Box components, which caused their Storybook pages to fail loading. To resolve this, I replaced those components with similar ones.

**Review by lordrip — APPROVED** [review]

**Comment by shivamG640** [comment]
Thanks @lordrip @lhein
