### PR TITLE
fix(xml-serializer): Recognise also steps and expressions defined by string

### LINKED ISSUE #1998: Bean's constructor not shown as expected
### Describe the Bug

Bean's constructor section not shown correctly on the UI

### Steps to Reproduce the Bug or Issue

Use the following XML
```
<camel xmlns="http://camel.apache.org/schema/spring" xmlns:s="http://www.springframework.org/schema/beans">
<beans>
    <bean name="xml-bean-from-registry" type="org.apache.camel.dsl.xml.io.beans.MyFacBean" factoryMethod="createBean">
        <constructors>
            <constructor value="Hello"/>
            <constructor value="Camel"/>
        </constructors>
        <properties>
            <property key="age" value="43"/>
        </properties>
    </bean>
</beans>
    <route id="r6">
        <from uri="direct:x6"/>
        <bean ref="xml-bean-from-registry" method="hi"/>
        <to uri="mock:y6"/>
    </route>

</camel>
```

In the beans tab, select the only bean, on the right, the constructor section is empty

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: Chrome
- Version: [e.g. 0.30.0]

### LINKED ISSUE #2084: URI configuration in Yaml camel route doesn't translate correctly into XML
### Describe the Bug

use e.g. this sample route:
```
- route:
    id: test-route
    from:
      uri: timer:start?period=1000&delay=2000&repeatCount=10
      steps:
        - setBody:
            constant: Initial message
        - to: log:info?showAll=true&multiline=true&logMask=true
        - transform:
            simple: ${body.toUpperCase()}
        - to: file:output?fileName=output.txt&fileExist=Append
```

the resulting XML route looks as follows:
```
<camel>
  <route id="test-route">
    <from uri="timer:start?period=1000&amp;delay=2000&amp;repeatCount=10"/>
    <setBody>
      <constant/>
    </setBody>
    <to/>
    <transform>
      <simple/>
    </transform>
    <to/>
  </route>
</camel>
```

### Steps to Reproduce the Bug or Issue

1. create Camel route with URI config
2. switch to XML
3. see the route is missing some of the URI configs

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

### PR DESCRIPTION
**Pull request by mmelko**
Changes:

-  - closes #2084 => implement the recognition of the steps and expressions defined only by string not only as a object, for example:

``` yaml 
 steps:
  - setBody:
      constant: Initial message
  - to: log:info?showAll=true&multiline=true&logMask=true
```  
  

- removing incorrect imports in some tests
-  fixed parsing beans constructors when index is not defined: fixes #1998
-  licenses updated

### CODE REVIEW

**Comment by lordrip** [comment]
@mmelko we need to take into consideration `log: ${body}` as well

**Comment by mmelko** [comment]
@lordrip I updated the PR to recognise all of the elements that can be defined by string and have required attribute (uri, pattern, name etc..)
Also I sneaked a fix for #1998  😇

File: packages/ui/src/serializers/xml/parsers/beans-xml-parser.ts [hunk 1]
```diff
@@ -50,12 +50,12 @@ export class BeansXmlParser {
...
 
-    Array.from(constructorsElement.children).forEach((constructorElement) => {
+    Array.from(constructorsElement.children).forEach((constructorElement, index) => {
       const constructorIndex = constructorElement.getAttribute('index');
       const constructorValue = constructorElement.getAttribute('value');
 
-      if (constructorIndex && constructorValue) {
-        constructors = { ...constructors, [constructorIndex]: constructorValue };
+      if (constructorValue) {
+        constructors = { ...constructors, [constructorIndex ?? index]: constructorValue };
```
Comment (mmelko) [inline packages/ui/src/serializers/xml/parsers/beans-xml-parser.ts:58]: this ensures that constructor is added when no index is defined and uses index from the objects forEarch.

**Comment by lordrip** [comment]
The original issue also affects how the Form reads the string-based EIPs definitions, so for that, we're gonna move forward with this PR and provide another one consolidating the fix for both scenarios at once.

**Comment by lordrip** [comment]
There's still an issue that we need to consider for the next PR:

Starting with this XML route
```xml
<camel>
  <route id="route-8014">
    <from id="from-8738" uri="timer:template?period=1000"/>
  </route>
  <beans>
    <bean name="hola" type="org.slf4j.Logger">
      <constructors>
        <constructor value="value-0"/>
        <constructor value="value-1"/>
      </constructors>
    </bean>
  </beans>
</camel>
```

Going to YAML, we see this:
```yaml
- route:
    id: route-8014
    from:
      id: from-8738
      uri: timer:template?period=1000
      steps: []
- beans:
    - constructors:
        "0": value-0
        "1": value-1
      name: hola
      type: org.slf4j.Logger
```

Notice how the URI in the `from` tag is not parsed into parameters.

**Review by lordrip — APPROVED** [review]
