### PR TITLE
fix(canvas): add droppable special child placeholders with insert-at-start capability

### LINKED ISSUE #2934: [drag-n-drop] Make choice container droppable while dragging when
### Description
With the changes introduced in this PR: https://github.com/KaotoIO/kaoto/pull/2877, we added support for container drag-and-drop. Containers can now be dragged and dropped onto other containers, edges, or placeholder nodes.
For example, a when container can be dragged and dropped directly onto another when container. However, there are still some limitations. At the moment, it is not possible to move a when container inside an empty choice container. The goal of this issue is to make such movements feasible.
The same limitation applies to other EIPs (e.g. doTry) and entities such as route configurations.

### Proposed approach
One possible solution is to always introduce a placeholder node inside containers like choice, even when they are empty, to enable direct drag-and-drop of child containers.

### PR DESCRIPTION
**Pull request by shivamG640**
Fixes #2934 

## Summary by CodeRabbit

* **New Features**
  * Added ability to insert predefined components and an "insert at start" option when adding steps.

* **Bug Fixes**
  * Improved drag-and-drop compatibility and placeholder-aware drop handling to prevent invalid drops and better handle forward/backward insertions/removals.

* **UI**
  * Clarified placeholder labels/tooltips, tightened placeholder spacing, added placeholder sizing defaults, and canvases now show additional per-branch placeholders.

* **Tests**
  * Expanded unit and E2E coverage for placeholder, drop and insertion flows; added a command to reset the canvas view.

### CODE REVIEW

**Comment by shivamG640** [comment]
@coderabbitai review

**Comment by shivamG640** [comment]
@coderabbitai review

**Comment by igarashitm** [comment]
When there's no step in `doTry` , it might be more intuitive to have `Add step` placeholder at first, before the `doCatch` one, to follow try-catch-finally flow
Screenshot From 2026-03-09 14-42-15

File: packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.tsx [hunk 1]
```diff
@@ -126,7 +125,21 @@ const PlaceholderNodeInner: FunctionComponent<PlaceholderNodeInnerProps> = obser
     return null;
   }
   const { onReplaceNode } = useReplaceStep(vizNode);
-  const { onInsertStep } = useInsertStep(vizNode, AddStepMode.InsertSpecialChildStep);
+  const isSpecialPlaceholder = vizNode.data.name !== 'placeholder' && vizNode.data.name !== 'placeholder-special-child';
```
Comment (igarashitm) [inline packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.tsx]: This `placeholder-special-child` string literal appears in several places. We might want to extract it to a exported constant and share.

File: packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.tsx [hunk 2]
```diff
@@ -126,7 +125,21 @@ const PlaceholderNodeInner: FunctionComponent<PlaceholderNodeInnerProps> = obser
...
+  const insertStepOptions = isSpecialPlaceholder
+    ? {
+        predefinedComponent: { name: vizNode.data.name, type: CatalogKind.Processor },
+        insertAtStart: true,
+      }
+    : undefined;
+  const { onInsertStep } = useInsertStep(insertStepTargetNode, AddStepMode.InsertSpecialChildStep, insertStepOptions);
+  const tooltipContent =
+    isSpecialPlaceholder || isSpecialChildPlaceholder
+      ? `Click to add ${vizNode?.data.name} branch`
```
Comment (igarashitm) [inline packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.tsx]: For `Rest` entity, it shows `placeholder-special-child` in tooltip

Image
