### PR TITLE
fix: Limiting the length of Node/Group/FlowsId(FlowMenu) labels

### LINKED ISSUE #789: Unable to click the 3 dots menu next to the step label if the label length is bigger than what can be displayed
### Describe the Bug

The option to expend the dropdown is displayed, when the name is shrunken, however, the dropdown can't be opened, as after the mouse hover on the three dots the name gets expanded. 

### Steps to Reproduce the Bug or Issue

1. add node, which name "shrinks", e.g. twitter-timeline-source
2. try to click the dropdown, when the name is not expanded

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/4180208/380c4a2f-db2e-471d-a7d2-af7ea46801a0

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

### PR DESCRIPTION
**Pull request by shivamG640**
Fixes #789

The changes can be test here: https://shivamg640.github.io/kaoto/

### CODE REVIEW

File: packages/ui/src/components/Visualization/Custom/CustomGroup.tsx [hunk 1]
```diff
@@ -35,7 +36,7 @@ const CustomGroup: FunctionComponent<ICustomGroup> = observer(({ element, ...res
         <DefaultGroup
           {...rest}
           element={element}
-          label={label}
+          label={doTruncateLabel(label)}
           truncateLength={15}
```
Comment (lordrip) [inline packages/ui/src/components/Visualization/Custom/CustomGroup.tsx:40]: I think we can remove this part now.
```suggestion
```

File: packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ describe('FlowsList.tsx', () => {
       </Provider>,
     );
     const flow1 = await wrapper.findByText('route-1234');
-    const flow2 = await wrapper.findByText('routeConfiguration-1234');
+    const flow2 = await wrapper.findByText('routeConfigu...');
```
Comment (lordrip) [inline packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx:54]: I think we can restore this file

File: packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx [hunk 3]
```diff
@@ -62,7 +63,7 @@ export const FlowsList: FunctionComponent<IFlowsList> = (props) => {
             <Td dataLabel={columnNames.current.id}>
               <InlineEdit
                 data-testid={`goto-btn-${flow.id}`}
-                value={flow.id}
+                value={doTruncateLabel(flow.id)}
```
Comment (lordrip) [inline packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx:66]: I think we can restore this file

File: packages/ui/src/utils/truncate-label.tsx [hunk 4]
```diff
@@ -0,0 +1,5 @@
+export const doTruncateLabel = (label: string | undefined): string | undefined => {
+  if (label === undefined) return;
+
+  return label.length > 15 ? label.substring(0, 12) + '...' : label;
```
Comment (lordrip) [inline packages/ui/src/utils/truncate-label.tsx:4]: Could you please check on the patternfly side if something like this is already provided?

File: packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx [hunk 5]
```diff
@@ -36,8 +39,12 @@ export const FlowsMenu: FunctionComponent = () => {
             <Icon isInline>
               <ListIcon />
             </Icon>
-            <span data-testid="flows-list-route-id" className="pf-v5-u-m-sm">
-              {visibleFlowsInformation().singleFlowId ?? 'Routes'}
+            <span data-testid="flows-list-route-id" className="pf-v5-u-m-sm flows-menu-display">
+              <Truncate
+                content={visibleFlowsInformation().singleFlowId ?? 'Routes'}
+                tooltipPosition={'top'}
```
Comment (lordrip) [inline packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx:45]:
```suggestion
                tooltipPosition="top"
```

**Review by lordrip — APPROVED** [review]
Great catch, and I like a lot the tooltip that shows the entire name :+1: 

image
